Becklyn/kaba

lib/kaba.js

Optionally add node_modules as sass include paths

---

tsconfig.json

Look at the commits one-by-one.

No strict typescript

---

lib/Kaba.js

| Bug fix?      |no
| New feature?  |no 

Remove useless code

---

bin/run.js
lib/CliConfig.js
lib/Kaba.js

| Bug fix?      |no
| New feature?  |no 
| Deprecations? |no 
| Docs PR       | https://github.com/Becklyn-Studios/docs/pull/21
Just always build source maps.

Always build Sourcemaps in JS

---

bin/run.js

It was already evaluated, but not added to the docs.
| Bug fix?      | yes
| Improvement?  |no  
| New feature?  |no 
| Deprecations? |no 
| Docs PR       | –

Add missing option

---

CHANGELOG.md
UPGRADE.md
lib/Kaba.js
tests/assets/js/a.js
tests/fixtures/ts/kaba.js

| Improvement?  | yes
| Deprecations? | yes

Always build TypeScript

---

CHANGELOG.md
bin/run.js
lib/Kaba.js
lib/runner/SassRunner.js
package.json

| Improvement?  | no  
| BC breaks?    | yes
Release everything for v8

Release v8

---

.eslintrc.yml
CHANGELOG.md

Use https://github.com/Becklyn/mojave/pull/205 instead.

Disallow prototype builtins

---

bin/run.ts
src/@types/kaba.d.ts

Move verbose into the CLI config

---

CHANGELOG.md
bin/run.ts
src/@types/kaba.d.ts
src/Kaba.ts

| New feature?  | yes
Improved the error handling of `node-sass` errors, to not catch too many errors.

Better sass errors [req #82]

---

CHANGELOG.md
src/Kaba.ts

| Bug fix?      | yes
| Improvement?  | no  

Fix module resolution + defined vars

---

CHANGELOG.md
src/Logger.ts

Add newlines in the log

---

CHANGELOG.md
configs/.eslintrc.yml
package.json
src/Kaba.ts

| Improvement?  | yes  
| Deprecations? | /no 

Autoimport fragment + bump dependencies

---

CHANGELOG.md
src/Kaba.ts

| New feature?  | /no 
| Docs PR       | **missing**

Only eslint files in the project dir

---

CHANGELOG.md
src/Kaba.ts

RELUCTANTLY add option to polyfill node core packages
| Improvement?  | no  
| New feature?  | yes 

Add option to polyfill node core packages

---

.github/pull_request_template.md
CHANGELOG.md
UPGRADE.md
package.json
src/Kaba.ts
src/runner/SassRunner.ts

| BC breaks?    | yes                                                                |
| Improvement?  | no     |

Remove chunk splitting

---

CHANGELOG.md
package.json
src/Kaba.ts

Enable cache loader

---

.travis.yml
CHANGELOG.md
package.json

Bump all dependencies + bump required node version

---

configs/tsconfig.legacy.json
configs/tsconfig.modern.json

| New feature?  | no                   |
| Improvement?  | yes    |
| Docs PR       | -                                  |
Use `esnext` for modules to support dynamic imports.

use esnext for modules

---

CHANGELOG.md
package.json
src/@types/kaba.d.ts
src/Kaba.ts
src/runner/WebpackRunner.ts

| New feature?  | yes                  |
| Improvement?  | no     |
| Deprecations? | no    |
| Docs PR       | **missing**                               |
Added a per entry file compiler.

Per entry compiler

---

CHANGELOG.md
package.json
src/Kaba.ts

Ignore CSS files when compiling

---

.travis.yml
package.json
src/Kaba.ts
tests/all_fixtures.js
tests/lib/runner.js

Compile auslese by default + bump all dependencies
